In [2]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([2, 3, 8, 9, 1, 7, 8, 4, 1, 6])

In [2]:
a[0]

4

In [3]:
a[-1]

0

In [4]:
a = np.random.randint(10, size = (3,5))

In [5]:
a

array([[0, 8, 6, 9, 9],
       [8, 8, 7, 4, 3],
       [9, 4, 0, 5, 8]])

In [6]:
a[0,0]

8

Slicing ile alt kümelere erişme

In [9]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
a[0:3] #slicing bu işte çok da bişeyi yok

array([20, 21, 22])

In [11]:
a[:3] #üsttekinin aynısı


array([20, 21, 22])

In [12]:
a[::2] #0dan başladı 1er atkayarak

array([20, 22, 24, 26, 28])

In [13]:
a[2::2] #2den başlayıp 2şer atlayarak

array([22, 24, 26, 28])

In [15]:
a = np.random.randint(10, size = (5,5))
a

array([[7, 3, 5, 6, 9],
       [6, 6, 8, 0, 4],
       [0, 4, 4, 5, 7],
       [3, 2, 4, 5, 3],
       [3, 0, 7, 7, 4]])

In [16]:
a[:,0] #vigülden öncesi satırları sonrası sütunları ifade ediyor
#yukarıdan aşağı tüm satırlar ve 0.sütun

array([7, 6, 0, 3, 3])

In [18]:
a[1:,0] #1.satırdan itibaren aşağıya doğru tüm satırlar ve 0.sütun

array([6, 0, 3, 3])

In [20]:
a[:,4] #yine aynı şekilde son sütunun tüm satırları

array([9, 4, 7, 3, 4])

In [21]:
a[0,:] #0.satırın tüm sütunları

array([7, 3, 5, 6, 9])

In [23]:
a[:2, :3] #2.indexteki satıra kadar ve 3.indexteki sütuna kadar seçildi

array([[7, 3, 5],
       [6, 6, 8]])

In [24]:
a[0:2, 0:3] # bir üsttekinin aynısı zaten karışıklık olmaması için
#böyle kullanmak daha iyi

array([[7, 3, 5],
       [6, 6, 8]])

In [25]:
a

array([[7, 3, 5, 6, 9],
       [6, 6, 8, 0, 4],
       [0, 4, 4, 5, 7],
       [3, 2, 4, 5, 3],
       [3, 0, 7, 7, 4]])

In [26]:
a[0:2, 0:] #ilk 2 satır ve onların tüm sütunları

array([[7, 3, 5, 6, 9],
       [6, 6, 8, 0, 4]])

In [28]:
a[0:, 0:2] #tüm satırların ilk 2 sütunu

array([[7, 3],
       [6, 6],
       [0, 4],
       [3, 2],
       [3, 0]])

In [29]:
a[1:3, 0:2]

array([[6, 6],
       [0, 4]])

In [30]:
#aşağıda göreceğiz ki a[1:3, 0:2]gibi alt kümeler seçip başka bir degere atarsak
#örn alt_kume=a[1:3, 0:2] ; biz bu alt kumede degisiklik yapınca a[]'nın
#orjinalinde de degisiklik oluyor evet biraz garip ama öyle

In [31]:
#örn
a

array([[7, 3, 5, 6, 9],
       [6, 6, 8, 0, 4],
       [0, 4, 4, 5, 7],
       [3, 2, 4, 5, 3],
       [3, 0, 7, 7, 4]])

In [35]:
alt_kume_a = a[0:2, 0:2]
alt_kume_a

array([[7, 3],
       [6, 6]])

In [36]:
alt_kume_a[0,0] = 99
alt_kume_a[1,1] = 99
alt_kume_a

array([[99,  3],
       [ 6, 99]])

In [39]:
a 
#goruldugu gibi orjinal a'da da 99lar geldi

array([[99,  3,  5,  6,  9],
       [ 6, 99,  8,  0,  4],
       [ 0,  4,  4,  5,  7],
       [ 3,  2,  4,  5,  3],
       [ 3,  0,  7,  7,  4]])

In [42]:
#böyle olmasını istemiyorsak, bu alt kümenin bağımsız
#oldugunu pythona copy()ile söyleriz.

alt_b = a[2:5, 2:5].copy()
alt_b

array([[4, 5, 7],
       [4, 5, 3],
       [7, 7, 4]])

In [45]:
alt_b[0,0] =99
alt_b[1,1] =99
alt_b[2,2] =99
alt_b 
#evet altkumede degisiklik yaptık

array([[99,  5,  7],
       [ 4, 99,  3],
       [ 7,  7, 99]])

In [46]:
a
#ve goruldugu gibi ana kümede degisiklik yok copy()ile 
#olusturdugumuz icin

array([[99,  3,  5,  6,  9],
       [ 6, 99,  8,  0,  4],
       [ 0,  4,  4,  5,  7],
       [ 3,  2,  4,  5,  3],
       [ 3,  0,  7,  7,  4]])

Fancy index

In [48]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
bu_indexleri_getir = np.array([1,3,5])

In [54]:
v[bu_indexleri_getir]

array([ 3,  9, 15])

In [52]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
satirda_istenen_indexler = np.array([0,1]) #0.satırve 1.sutun kesisimi
sutunda_istenen_indexler = np.array([1,2]) #1.satır ve 2. sutun kesisimi

In [56]:
m[satirda_istenen_indexler, sutunda_istenen_indexler]

array([1, 5])

In [57]:
#asagida hem basit index secme hem fancy index kullanacaz

m[0, [1,2]] #sıfırıncı satırın 1.sutun ve 2.sutunla kesisimi

array([1, 2])

In [62]:
m[0:, [1,2]] #bütün satırlar(bütun yataylar ve 1ve2. sutunun kesisimleri)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
c = np.arange(10,20)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [69]:
c[index]

array([10, 11, 12])

In [71]:
c[index] = 99 #fancy index ile birden fazla indexi secip
#ayni anda degistirdik
c

array([99, 99, 99, 13, 14, 15, 16, 17, 18, 19])

In [72]:
c[index] = 99 ,100 ,101 #hepsini aynı degere atamak zorunda degiliz

In [73]:
c

array([ 99, 100, 101,  13,  14,  15,  16,  17,  18,  19])