In [2]:
import numpy as np

In [3]:
v = np.array([4,2,5,7,1])
v

array([4, 2, 5, 7, 1])

In [4]:
np.sort(v) #normal düz pythonda sort metodu kullansaydık
# arrayin yapısı direkt degisecekti arrayin ilk hali kaybolacakti ancak numpyda
#sort kullanınca degismiyor yapisi istersen baska biseye atayabilirsin

array([1, 2, 4, 5, 7])

In [5]:
v

array([4, 2, 5, 7, 1])

In [6]:
i = np.argsort(v)#siralama yapilinca indexlerde olan degisimi gosterir

In [7]:
i

array([4, 1, 0, 2, 3])

In [8]:
#ustteki böyle okunur:
#orjinalinde sıfırıncı indexte olan; 
#sıralama sonrasi 4e,
#birinci indexte olan 1e,
#2.indexte olan 0a,
#3.indexte olan 2ye,
#4.indexte olan e3 gitmistir yeni halde

In [11]:
v

array([4, 2, 5, 7, 1])

In [12]:
v[i] #vnin i'inci elemani seklinde yapinca indexe göre siraladik

array([1, 2, 4, 5, 7])