# *****Numpy

## Array creating

import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a*b

In [4]:
who

a	 b	 np	 


#Numpy Array Olusturma

##Listelerden Array Olusturma

In [5]:
import numpy as np

np.array([3.14, 4, 6, 12.22])

array([ 3.14,  4.  ,  6.  , 12.22])

In [6]:
np.array([3.14, 4, 6, 12.22], dtype="float32")

array([ 3.14,  4.  ,  6.  , 12.22], dtype=float32)

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [11]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,1,30) #0 ile 1 arasında 30 tane deger olustur

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [13]:
np.random.normal(0,1, (3,4)) #ortalamsı 0, varyansı 1 olan 3e4lük matris(2boyutlu dizi)

array([[-0.12107933,  0.88240313, -0.18856398, -1.76969795],
       [-1.03109951, -0.13609638,  2.50319065, -0.33409644],
       [ 1.08220755,  0.90959769,  0.11906943,  1.08286785]])

In [14]:
np.random.randint(0,10, (2,2)) #0 ile 10 arasında sayılardan oluan rastgele 2ye2lik dizi

array([[7, 5],
       [6, 8]])

In [15]:
np.eye(3) #köşegen elemanları 1 olan 3 ölçülük matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(4)#köşegen elemanları 1 olan 4 ölçülük matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])