Numpy Bicimlendirme

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi

In [1]:
import numpy as np

a = np.random.randint(10, size = 10)
#tek boyutlu bir array
a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [8]:
b = np.random.randint(20, size = (10,5))
#iki boyutlu bir array(10 tane 5 uzunluğunda satır, 1den 10akadar)

In [9]:
b.ndim

2

In [10]:
b

array([[ 9,  1, 11, 13, 18],
       [12,  8, 19, 14, 18],
       [17, 15, 18, 10, 13],
       [ 7,  2, 18,  5,  4],
       [ 4, 10, 15, 16, 11],
       [ 1,  0,  0, 15,  4],
       [17, 13, 16, 19, 19],
       [ 5,  5,  6, 10,  7],
       [13,  1, 14,  8, 19],
       [17, 18,  9, 12,  2]])

In [5]:
b.size

50

In [6]:
b.dtype

dtype('int64')

In [11]:
a = np.random.randint(10, size = (3,5,2))
#3 boyutlu bir dizi

In [12]:
a.ndim

3

In [13]:
a


array([[[8, 9],
        [4, 8],
        [5, 1],
        [3, 2],
        [1, 8]],

       [[8, 8],
        [6, 6],
        [3, 1],
        [5, 3],
        [9, 3]],

       [[4, 2],
        [7, 0],
        [6, 4],
        [2, 3],
        [2, 1]]])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10).reshape((3,3))
#yukarıdaki 1den 10a kadar olan arrayi
#reshape diyerek yeniden şekillendirip 3e3lük yaptık
#şeklini , dimensionunu (ndim)inini degistrdik

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
c = np.array([1,2,3])

In [24]:
c

array([1, 2, 3])

In [25]:
c.ndim

1

In [20]:
d = c.reshape((1,3))

In [26]:
d

array([[1, 2, 3]])

In [27]:
d.ndim

2

In [29]:
#iki tane koseli parantezin icine yazılmıs olması sunu gosterir;
#goruldugu gibi reshape ile tek satırlı olan vektör olan
#arrayi de 2 boyutlu yaptık
#vektor formunda kaldı ama bilgisayar artık onu matris olarak dusunuyır

In [30]:
c

array([1, 2, 3])

In [31]:
c[np.newaxis, :]

array([[1, 2, 3]])

In [32]:
#bu seiklde de usttekinin aynisni yaptık

In [33]:
c[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [34]:
#aynisini tersten yazarak satır vektoru degil de
#sutun vektoru yaptik

In [35]:
c.shape

(3,)