In [2]:
import numpy as np

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a-1 #her elemandan 1 çıkarır

array([-1,  0,  1,  2,  3,  4])

In [4]:
a**2

array([ 0,  1,  4,  9, 16, 25])

In [5]:
a%2 #2ye bölümden kalanlar

array([0, 1, 0, 1, 0, 1])

In [6]:
a

array([0, 1, 2, 3, 4, 5])

**Bu işlemlerin fonksiyon karşılığı da var

In [8]:
np.add(a,2) #her elemana 2 ekle

array([2, 3, 4, 5, 6, 7])

In [9]:
np.subtract(a,1) #her elemandan 1 çıkar

array([-1,  0,  1,  2,  3,  4])

In [10]:
np.power(a,3) #kuvvet alma

array([  0,   1,   8,  27,  64, 125])

In [12]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [14]:
np.add.reduce(a) #reduce tek değere indirgemek anlamına geliyor biliyoruz
#add ile birleşince hepsini topyalıp tek değerde yazdırdı

15

In [15]:
np.add.accumulate(a) #üsttekinin aynısını yapar yan elemanları
#birbiri ile toplar ancak bu işlemin her basamağını iteratif olarak
#döndürür ki kullanabilelim

array([ 1,  3,  6, 10, 15])

In [16]:
a = np.random.normal(0,1,30)
a

array([-1.83858841, -0.28350078, -0.52884584, -2.61738591, -0.37209077,
       -0.66341013, -0.97504603,  0.55500125, -0.89486696,  1.2393447 ,
       -0.61377303,  1.4806657 ,  0.52027162, -0.71278239,  1.06123936,
        0.84203681,  0.15173785, -1.08566407,  0.0402435 ,  0.74785639,
       -0.64587717, -0.62325084, -0.20433862, -0.0137027 , -0.48841473,
        1.59127748,  1.5358021 ,  0.48525782,  0.3233367 , -0.42662891])

In [17]:
np.mean(a) #anın ortalaması

-0.0804698670368064

In [18]:
np.std(a) #standart sapma

0.9663614401869691

In [19]:
np.var(a) #varyans

0.9338544330802332

In [20]:
np.median(a) #medyan

-0.24391970322330175

In [21]:
np.min(a) #minimum deger

-2.6173859121610983

In [23]:
np.max(a) #max deger

1.5912774832260137

** Aşağıdaki fonksiyonlar bu işlemleri eksik değerlere duyarlı olarak yaparlar**

*np.nanmean(a)

*np.nanstd(a)

*np.nanvar(a)

*np.nanargmin(a)

*np.nanargmax(a)

*np.nanmedian(a)

In [25]:
#asagida da tek boyutlu olmayanlarda islem yapacagiz

In [27]:
a = np.random.normal(0,1, (3,3))
a

array([[-1.22137026, -1.00311908, -0.97155187],
       [-0.41018106, -1.63433309,  0.16143548],
       [-1.69013735, -1.03471151, -0.86065897]])