# NumPy

Why NumPy ? 

* Numpy arrays supports only single data type per array while python's standard arrays can contain every type in one array. If a standard python array contains 20 data, it has 20 info for data types of each data while numpy has only one. This makes NumPy 20 times faster in this case.

## Specs of Numpy Arrays

* ndim: dimension quantity
* shape: dimension info like 4x5, 7x2 etc.
* size: total item quanitity
* dtype: arrays data type

In [33]:
a = np.random.randint(10, size=(4,5))
a

array([[8, 9, 9, 9, 1],
       [1, 5, 1, 1, 6],
       [2, 2, 8, 8, 7],
       [0, 3, 7, 5, 8]])

In [34]:
a.ndim # 2D array

2

In [36]:
a.shape # 2D 4x5 array

(4, 5)

In [38]:
a.size # Total item quantity

20

## Creating numpy array

In [23]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [3]:
np.array([3.14, 5, 9, 24])
# Since numpy arrays support only one type, all numbers are decimal

array([ 3.14,  5.  ,  9.  , 24.  ])

In [5]:
np.array([5.875, 92, 33, 17], dtype="int")
# Since we declared the type, all numbers turned into int

array([ 5, 92, 33, 17])

### Creating filled arrays from scratch

* np.arange(start, stop, evenly space by x)
* np.linspace(start, stop, how many numbers you want)

In [9]:
np.zeros(10, dtype="int") # Create 1D array with 10 zeros.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.full((4,8), 16) # Create 4x8 array with 16's

array([[16, 16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16, 16]])

In [17]:
np.arange(0,36, 5) # Create an array from the numbers between 0-36 evenly spaced 5 by 5

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [20]:
np.linspace(0,35, 8, dtype="int") # Create an array contains evenly spaced 8 number between 0,35

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [22]:
np.random.randint(0,10, (3,3)) # Create an 3x3 array contains random numbers between 0,10

array([[3, 9, 8],
       [8, 1, 8],
       [3, 9, 5]])

## Reshaping arrays

In [39]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [42]:
a.ndim

1

In [44]:
b = a.reshape((1,4))
b

array([[1, 2, 3, 4]])

In [46]:
b.ndim # While content staying same, we can change dimension quantity

2

## Array Concatenation

* np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

In [14]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

### 2D Concatenation

In [24]:
x = np.array([[1,2,3],
              [4,5,6]])

np.concatenate((x,x), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
x = np.array([[1,2,3],
              [4,5,6]])

np.concatenate((x,x), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Splitting

* np.split(array, SectionsOrIndexesThatWillSplit, axis=0)
* np.hsplit(array, SectionsOrIndexesThatWillSplit) horizantally-column based
* np.vsplit(array, SectionsOrIndexesThatWillSplit) vertically-row based

In [26]:
import numpy as np

x = np.array([1,2,3,99,99,4,5,6])

np.split(x, [3,5]) # 0 to 3 then, 3 to 5, then 5 to the end

[array([1, 2, 3]), array([99, 99]), array([4, 5, 6])]

In [27]:
a,b,c = np.split(x, [3,5]) # 0 to 3 then, 3 to 5, then 5 to the end

In [28]:
a

array([1, 2, 3])

In [29]:
b

array([99, 99])

In [30]:
c

array([4, 5, 6])

### 2D Splitting

In [31]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [34]:
np.vsplit(a, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## Sorting

* np.sort(array, axis = -1, kind=None, order=None)
* kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional

* "mergesort" is quick and stable since it's bigO notation is O(n*log(n))
* "heapsort" is fastest but not stable

In [37]:
import numpy as np

a = np.array([3,27,8,5,12])

np.sort(a, kind="mergesort")

array([ 3,  5,  8, 12, 27])

### 2D sorting

In [40]:
a = np.random.randint(10, size=(4,5))
a

array([[4, 4, 0, 9, 1],
       [6, 6, 4, 6, 3],
       [1, 3, 1, 2, 9],
       [0, 6, 9, 7, 3]])

In [41]:
np.sort(a, axis=0) # Sorted each column

array([[0, 3, 0, 2, 1],
       [1, 4, 1, 6, 3],
       [4, 6, 4, 7, 3],
       [6, 6, 9, 9, 9]])

In [43]:
np.sort(a, axis=1) # Sorted each row

array([[0, 1, 4, 4, 9],
       [3, 4, 6, 6, 6],
       [1, 1, 2, 3, 9],
       [0, 3, 6, 7, 9]])

# Indexing & Accessing